$id: "https://github.com/dodona-edu/universal-judge/blob/master/tested/dsl/schema.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
title: "DSL Schema"
description: "YAML DSL TESTed testplan"
oneOf:
  - $ref: "#/definitions/_rootList"
  - $ref: "#/definitions/_rootObject"
definitions:
  _rootList:
    type: "array"
    minItems: 1
    items:
      $ref: "#/definitions/tab"
  _rootObject:
    type: "object"
    properties:
      config:
        $ref: "#/definitions/globalConfig"
        description: "Configuration settings at plan level"
      disableOptimizations:
        type: "boolean"
        description: "Disable performance optimizations"
      namespace:
        type: "string"
        default: "submission"
        description: "Namespace of the submitted solution, best in `snake_case`"
      tabs:
        type: "array"
        descriptions: "List of all tabs to test"
        items:
          $ref: "#/definitions/tab"
    required:
      - "tabs"
  configGeneral:
    hideExpected:
      description: "Hide the expected value in feedback (default: false), not recommended to use!"
      type: "boolean"
    required:
      - "hideExpected"
  configText:
    type: "object"
    description: >-
      Configuration properties for textual comparison and to configure if the expected value should be hidden or not
    minProperties: 1
    properties:
      applyRounding:
        description: "Apply rounding when comparing as float"
        type: "boolean"
      caseInsensitive:
        description: "Ignore case when comparing strings"
        type: "boolean"
      ignoreWhitespace:
        description: "Ignore leading and trailing whitespace"
        type: "boolean"
      roundTo:
        description: "The number of decimals to round at, when applying the rounding on floats"
        type: "integer"
      tryFloatingPoint:
        description: "Try comparing text as floating point numbers"
        type: "boolean"
      hideExpected:
        description: "Hide the expected value in feedback (default: false), not recommended to use!"
        type: "boolean"
  localConfigGeneral:
    type: "object"
    description: "General configuration properties for one test"
    required:
      - "data"
      - "config"
    properties:
      data:
        $ref: "#/definitions/textualTypes"
      config:
        $ref: "#/definitions/configGeneral"
  localConfigText:
    type: "object"
    description: "Textual configuration properties of one test"
    required:
      - "data"
      - "config"
    properties:
      data:
        $ref: "#/definitions/textualTypes"
      config:
        $ref: "#/definitions/configText"
  globalConfig:
    type: "object"
    description: "Global configuration properties"
    minProperties: 1
    properties:
      stdout:
        $ref: "#/definitions/configText"
      stderr:
        $ref: "#/definitions/configText"
      exception:
        $ref: "#/definitions/configGeneral"
      exitCode:
        $ref: "#/definitions/configGeneral"
      return:
        $ref: "#/definitions/configGeneral"
  streamOutput:
    anyOf:
      - $ref: "#/definitions/textualTypes"
      - $ref: "#/definitions/localConfigText"
  generalOutput:
    anyOf:
      - $ref: "#/definitions/textualTypes"
      - $ref: "#/definitions/localConfigGeneral"
  file:
    type: "object"
    description: "Tab definition with testcases"
    required:
      - "name"
      - "url"
    properties:
      name:
        type: "string"
        description: "File name"
      url:
        type: "string"
        format: "uri"
        description: "Relative path to the file in the `description` folder of a Dodona exercise"
  tab:
    type: "object"
    description: "Tab definition with runs"
    properties:
      config:
        $ref: "#/definitions/globalConfig"
        description: "Configuration settings at tab level"
      hidden:
        type: "boolean"
        description: "Defines if the tab is hidden for the student or not"
      tab:
        type: "string"
        description: "Name for the tab on Dodona"
      contexts:
        type: "array"
        description: "Context test sequence"
        items:
          $ref: "#/definitions/context"
    required:
      - "contexts"
      - "tab"
  context:
    type: "object"
    description: "Information to execute one context"
    anyOf:
      - oneOf:
          - anyOf:
              - required:
                  - "testcases"
              - required:
                  - "arguments"
              - required:
                  - "exitCode"
              - required:
                  - "stdin"
          - $ref: "#/definitions/testcase"
      - anyOf:
          - required:
              - "exception"
          - required:
              - "stdout"
          - required:
              - "stderr"
    properties:
      config:
        $ref: "#/definitions/globalConfig"
        description: "Configuration settings at context level"
      files:
        type: "array"
        items:
          $ref: "#/definitions/file"
      testcases:
        type: "array"
        description: "Array of statements and expression tests"
        minItems: 1
        items:
          $ref: "#/definitions/testcase"
      arguments:
        type: "array"
        description: "Array of program call arguments"
        items:
          $ref: "#/definitions/textualTypes"
      exception:
        description: "Expected exception for main call"
        $ref: "#/definitions/textualTypes"
      exitCode:
        type:  ["integer", "object"]
        description: "Expected exit code for the run"
        required:
          - "data"
          - "config"
        properties:
          data:
            type: "integer"
          config:
            $ref: "#/definitions/configGeneral"
      stdin:
        description: "Given input at stdin for main call"
        $ref: "#/definitions/textualTypes"
      stderr:
        description: "Expected output for main call at stderr"
        $ref: "#/definitions/streamOutput"
      stdout:
        description: "Expected output for main call at stdout"
        $ref: "#/definitions/streamOutput"
  testcase:
    type: "object"
    description: "An individual test for a statement or expression"
    properties:
      exception:
        description: "Expected exception message"
        $ref: "#/definitions/generalOutput"
      files:
        type: "array"
        items:
          $ref: "#/definitions/file"
      return:
        description: "Expected return value"
        anyOf:
          - type: "array"
          - type: "boolean"
          - type: "integer"
          - type: "null"
          - type: "number"
          - type: "object"
          - type: "string"
      return-raw:
        description: "Value string to parse to the expected return value"
        $ref: "#/definitions/generalOutput"
      statement:
        description: "Statement or expression to evaluate"
        $ref: "#/definitions/textualTypes"
      expression:
        description: "Statement or expression to evaluate"
        $ref: "#/definitions/textualTypes"
      stderr:
        description: "Expected output at stderr"
        $ref: "#/definitions/streamOutput"
      stdout:
        description: "Expected output at stdout"
        $ref: "#/definitions/streamOutput"
      config:
        $ref: "#/definitions/globalConfig"
        description: "Configuration settings at testcase level"
    oneOf:
      - required:
          - "statement"
      - required:
          - "expression"
    dependencies:
      return:
        not:
          required:
            - "return-raw"
      return-raw:
        not:
          required:
            - "return"
      statement:
        not:
          required:
            - "expression"
      expression:
        not:
          required:
            - "statement"
  textualTypes:
    anyOf:
      - type: "boolean"
      - type: "integer"
      - type: "number"
      - type: "string"
