name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt -r requirements-test.txt
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install GHC 8.10
        uses: actions/setup-haskell@v1.1.4
        id: setup-haskell-cabal
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.4'
      - uses: actions/cache@v2
        id: cache-cabal
        name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-cabal-aeson.2021.03.30
          restore-keys: |
            ${{ runner.os }}-cabal-
      - name: Install Haskell dependencies
        run: cabal v1-install aeson
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@bb0e1ead85a7f840e9d2bc4bdd2c3950b080a449
      - name: Run tests
        run: |
          python -m pytest tests/ -m "not slow and not flaky"
