name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt -r requirements-test.txt
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install GHC 8.10
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.4'
      - name: Install Haskell dependencies
        run: cabal v1-install aeson
      - uses: actions/cache@v2
        name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-aeson
          restore-keys: |
            ${{ runner.os }}-cabal-
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@bb0e1ead85a7f840e9d2bc4bdd2c3950b080a449
      - name: Run tests
        run: |
          python -m pytest tests/ -m "not slow and not flaky"
