name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix flake check --print-build-logs
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop .#format -c poetry run isort --check-only ./tested ./tests
      - run: nix develop .#format -c poetry run black --check ./tested ./tests
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop .#types -c pyright ./tested
