name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop -c poetry run pytest -n auto --cov=tested --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop -c poetry run isort ./tested ./tests
      - run: nix develop -c black ./tested ./tests
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop -c pyright ./tested
