name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - uses: actions/cache@v2
        name: Cache pip
        # Idea: https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt -r requirements-test.txt -r tested/languages/python/requirements.txt
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install GHC 8.10
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.4'
      - uses: actions/cache@v2
        name: Cache cabal
        with:
          path: |
            ~/.cabal
            ~/.ghc
            dist-newstyle
          key: ${{ runner.os }}-cabalghc-20210330
          restore-keys: |
            ${{ runner.os }}-cabalghc-
            ${{ runner.os }}-cabal-
      - name: Install Haskell dependencies
        run: cabal v1-install aeson
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@bb0e1ead85a7f840e9d2bc4bdd2c3950b080a449
      - name: Install linters
        run: >
          sudo apt -y install hlint=2.1.11-1build4 cppcheck=1.90-4build1 shellcheck=0.7.0-2build2 &&
          sudo npm install -g eslint@7.23.0
      - name: Run tests
        run: |
          python -m pytest tests/ -m "not slow and not flaky"
