name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-test.txt -r tested/languages/python/requirements.txt
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.6'
      - uses: actions/cache@v3
        name: Cache cabal
        with:
          path: |
            ~/.cabal
            ~/.ghc
            dist-newstyle
          key: ${{ runner.os }}-ghc-9.2.1-20220111
          restore-keys: |
            ${{ runner.os }}-ghc-9.2.1-
      - run: cabal v1-install aeson
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install abstract-syntax-tree@2.20
      - run: npm install -g eslint@8.7
      - run: sudo apt -y install hlint cppcheck shellcheck checkstyle
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.43.2/ktlint && chmod a+x ktlint
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: python -m pytest tests/ -m "not flaky"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "~= 22.0"
          src: "./tested ./tests"
