name: JavaScript integration tests

on: [ workflow_dispatch ]

jobs:
  # Runs all our JavaScript exercises against TESTed to check if they are still correct.
  # This is also done in the Docker, since this is hard to do in Nix.
  javascript-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git clone git@github.ugent.be:Scriptingtalen/javascript-oefeningen.git
      - run: git checkout 4a2094135abe972eb38072be129171f685c18ec3
        working-directory: ./javascript-oefeningen
      - run: docker build -t "integration-image" -f ${{ github.workspace }}/.github/dodona-image-integration.dockerfile --network=host .
        name: Build Dodona Docker image
      - run: docker run -v ${{ github.workspace }}:/github/workspace -e TESTED_SOURCE=/github/workspace -e EXERCISE_REPO=/github/workspace/javascript-oefeningen integration-image
        name: Run integration tests in Dodona Docker image
